---
title: "p8105_hw6_yd2739"
author: "Yuxuan Du"
date: "2023-11-17"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
```

## Problem 1

```{r}
homicides_data = read_csv('https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv')|>
  mutate(city_state = paste(city, state, sep = ", "))|>
  group_by(city_state)|>
  subset(city_state != "Dallas, TX")|>
  subset(city_state != "Phoenix, AZ")|>
  subset(city_state != "Kansas City, MO")
```

```{r}
homicides_data_cleaned = homicides_data|>
  mutate(case_solved = ifelse(disposition!="Open/No arrest", 1, 0))|>
  filter(victim_race == "White"|victim_race == "Black")|>
  mutate(victim_age = as.numeric(victim_age))
```

```{r}
Baltimore_df = homicides_data_cleaned|>
  subset(city_state == "Baltimore, MD")|>
  mutate(victim_race = factor(victim_race))|>
  mutate(victim_sex = factor(victim_sex))

fit_logistic = 
  Baltimore_df|> 
  glm(case_solved ~ victim_age + victim_race + victim_sex, data = _, family = binomial())

fit_logistic|>
  broom::tidy()|> 
  filter(term == "victim_sexMale")|>
  mutate(
    OR = exp(estimate),
    LowerCI = exp(estimate - 1.96 * std.error),
    UpperCI = exp(estimate + 1.96 * std.error)
  )
```


```{r}
fit_glm_for_city = function(city_data) {
  fit_logistic = glm(case_solved ~ victim_age + victim_race + victim_sex, data = city_data, family = binomial())
  tidy_result = fit_logistic|>
    broom::tidy()|>
    filter(term == "victim_sexMale")|>
    mutate(
      OR = exp(estimate),
      LowerCI = exp(estimate - 1.96 * std.error),
      UpperCI = exp(estimate + 1.96 * std.error)
    )|>
    select(term, OR, LowerCI, UpperCI)
}

result_list = homicides_data_cleaned |>
  mutate(victim_race = factor(victim_race))|>
  mutate(victim_sex = factor(victim_sex))|>
  group_by(city_state) |>
  nest()|>
  filter(city_state != "Tulsa, AL")|>
  mutate(glm_result = map(data, fit_glm_for_city))|>
  unnest(glm_result)
```

```{r}
result_list|>
  ggplot(aes(x = reorder(city_state, OR), y = OR))+
  geom_point() +
  geom_errorbar(aes(ymin = LowerCI, ymax = UpperCI), width = 0.2) +
  coord_flip() +  # Flips the axes to make the cities display horizontally
  labs(title = "Estimated ORs and CIs for Solving Homicides by City",
       x = "City",
       y = "Adjusted Odds Ratio (OR)")
```

## Problem 2

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

```{r}
boot_straps_result = 
  weather_df |> 
  modelr::bootstrap(n = 5000)|>
  mutate(
    models = map(strap, \(df) lm(tmax ~ tmin + prcp, data = df)),
    results = map(models, broom::tidy), 
    glance = map(models, broom::glance))|>
  select(-strap, -models)
  

betas_result = boot_straps_result|>
  unnest(results)|>
  group_by(.id)|>
  filter(term != "(Intercept)")|>
  summarize(coefficient_product = prod(estimate))|>
  mutate(log_coefficient_product = log(coefficient_product))
    
r_squared_result = boot_straps_result|>
  unnest(glance)|>
  subset(select = c(.id, r.squared))
```

```{r}
p2_result = left_join(betas_result, r_squared_result, by = ".id")
```

## Problem 3
```